apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  template:
    spec:
      containers:
        - image: 442426896735.dkr.ecr.ap-south-1.amazonaws.com/app-backend:15176e9065e7e1db0bda0b64d0c47a6ef9169bdd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 442426896735.dkr.ecr.ap-south-1.amazonaws.com/app-backend:15176e9065e7e1db0bda0b64d0c47a6ef9169bdd # <-- YOUR NEW HEART!
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-credentials
