apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  template:
    spec:
      containers:
        - image: 442426896735.dkr.ecr.ap-south-1.amazonaws.com/app-frontend:61ecc85705e204d430845be30df0e3676ac36639
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 442426896735.dkr.ecr.ap-south-1.amazonaws.com/app-frontend:61ecc85705e204d430845be30df0e3676ac36639 # <-- YOUR NEW IMAGE!
          ports:
            - containerPort: 80
