apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data: # Content here is to be filled 
  # Replace with your base64 encoded username
  username: YOUR_BASE64_ENCODED_USERNAME
  # Replace with your base64 encoded password
  password: YOUR_BASE64_ENCODED_PASSWORD
